// Mocks generated by Mockito 5.4.4 from annotations
// in games/test/auth_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;

import 'package:games/services/auth_service.dart' as _i3;

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i3.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.User? get currentUser =>
      (super.noSuchMethod(Invocation.getter(#currentUser)) as _i2.User?);

  @override
  Stream<_i2.AuthState> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: Stream<_i2.AuthState>.empty(),
        returnValueForMissingStub: Stream<_i2.AuthState>.empty(),
      ) as Stream<_i2.AuthState>);

  @override
  Future<_i2.AuthResponse> signUp({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: Future<_i2.AuthResponse>.value(_i2.AuthResponse()),
        returnValueForMissingStub:
            Future<_i2.AuthResponse>.value(_i2.AuthResponse()),
      ) as Future<_i2.AuthResponse>);

  @override
  Future<_i2.AuthResponse> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: Future<_i2.AuthResponse>.value(_i2.AuthResponse()),
        returnValueForMissingStub:
            Future<_i2.AuthResponse>.value(_i2.AuthResponse()),
      ) as Future<_i2.AuthResponse>);

  @override
  Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(#signOut, []),
        returnValue: Future<void>.value(),
        returnValueForMissingStub: Future<void>.value(),
      ) as Future<void>);
}
