// Mocks generated by Mockito 5.4.4 from annotations
// in games/test/spin_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;

import 'package:games/models/spin_reward.dart' as _i2;
import 'package:games/services/ad_service.dart' as _i3;
import 'package:games/services/spin_service.dart' as _i4;

/// A class which mocks [AdService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdService extends _i1.Mock implements _i3.AdService {
  MockAdService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAdLoaded =>
      (super.noSuchMethod(Invocation.getter(#isAdLoaded),
          returnValue: false) as bool);

  @override
  Future<void> loadAd() => (super.noSuchMethod(
        Invocation.method(#loadAd, []),
        returnValue: Future<void>.value(),
        returnValueForMissingStub: Future<void>.value(),
      ) as Future<void>);

  @override
  Future<_i3.AdResult> showAd() => (super.noSuchMethod(
        Invocation.method(#showAd, []),
        returnValue: Future<_i3.AdResult>.value(_i3.AdResult.failed),
        returnValueForMissingStub:
            Future<_i3.AdResult>.value(_i3.AdResult.failed),
      ) as Future<_i3.AdResult>);
}

/// A class which mocks [SpinService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpinService extends _i1.Mock implements _i4.SpinService {
  MockSpinService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Future<_i4.SpinSession> fetchOrCreateSession() => (super.noSuchMethod(
        Invocation.method(#fetchOrCreateSession, []),
        returnValue: Future<_i4.SpinSession>.value(
          _i4.SpinSession.fresh('2024-01-15'),
        ),
        returnValueForMissingStub: Future<_i4.SpinSession>.value(
          _i4.SpinSession.fresh('2024-01-15'),
        ),
      ) as Future<_i4.SpinSession>);

  @override
  Future<_i4.SpinSession> recordSpin({
    required _i2.SpinReward? reward,
    required _i4.SpinSession? currentSession,
    required bool? isAdSpin,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordSpin,
          [],
          {
            #reward: reward,
            #currentSession: currentSession,
            #isAdSpin: isAdSpin,
          },
        ),
        returnValue: Future<_i4.SpinSession>.value(
          _i4.SpinSession.fresh('2024-01-15'),
        ),
        returnValueForMissingStub: Future<_i4.SpinSession>.value(
          _i4.SpinSession.fresh('2024-01-15'),
        ),
      ) as Future<_i4.SpinSession>);

  @override
  Future<_i4.SpinSession> recordAdWatched(_i4.SpinSession? currentSession) =>
      (super.noSuchMethod(
        Invocation.method(#recordAdWatched, [currentSession]),
        returnValue: Future<_i4.SpinSession>.value(
          _i4.SpinSession.fresh('2024-01-15'),
        ),
        returnValueForMissingStub: Future<_i4.SpinSession>.value(
          _i4.SpinSession.fresh('2024-01-15'),
        ),
      ) as Future<_i4.SpinSession>);
}
